# Generated by Django 5.0.6 on 2024-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energy_consumption', models.FloatField()),
                ('renewable_availability', models.FloatField()),
                ('fossil_fuel_usage', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
